### ISSUE TITLE
really secure?!

### ISSUE THREAD

**Issue by Ghostboy-287** [bitbeans/SimpleDnsCrypt#120]
Hello

Are dnscrypt proxies truly secure?
Because when I do a dnsleak test, I don't like to see too many host names: /
a thing that i see in all the proposed proxies here.

Thank you for enlightening me on this subject
And how can i send you proxies (i have some premium ones)

**Comment by EMLVIRUS** [comment]
DNSCrypt only effects info transfer on DNS recursive query to prevent DNS spoofing. It is NOT designed to be an online security tool though DNS pollution can be a plausible online attack.

**Comment by zymase** [comment]
@Ghostboy-287 the results of a dnsleak test reflect the DNS resolver's host names.
i.e. if you choose cisco, dnscrypt.eu-nl and many others the dnsleak test will show one host, but other resolvers such as adguard-dns-ns1, adguard-dns-ns2 and several others will show several hosts because those resolvers delegate their search to other resolvers (Google, Yandex, OpenDNS...). It's up to the user to choose the resolver, as you know.

**Comment by EMLVIRUS** [comment]
@zymase That's what I mean actually. DNSCrypt will only ensure you get proper DNS response. It comes with NO security assurance.

**Comment by Themercee** [comment]
Does DNSCrypt also ensure that nobody is eavesdropping on the communication between the DNS and the Resolver? With the new law from US, it could be a useful feature :P
