### ISSUE TITLE
Does this vulnerability exist

### ISSUE THREAD

**Issue by rdbox** [bitbeans/SimpleDnsCrypt#140]
Not so long ago I read that there is a **DNS Amplification attack ** vulnerability in DNSSEC
**_Is your program closed?_**

**Comment by CHEF-KOCH** [comment]
Yes, Attackers abuse open resolvers by sending a barrage of spoofed DNS queries where the IP source is set to be the MIT target IP. Most of these servers will cache the initial response so multiple queries are not made to the authoritative name servers.

In fact this is protocol related, because not only DNS is affected. The NTP, CHARGEN and SSDP protocols are also commonly used in such attacks and, unfortunately, as long as misconfigured servers and devices are available on the Internet, this technique will continue to be favored by attackers.

**Comment by jedisct1** [comment]
This is an urban legend spread by companies whose services don't support DNSSEC.

DNS amplification doesn't require DNSSEC at all.

Returning many large records is all it takes, and people conducting attacks understood this very well and set up dedicated zones returning such large responses. Without DNSSEC.

As stated by Chef-Koch, many other protocols are abused the same way.

That being said, the DNSCrypt protocol prevents amplification, as it requires questions to be at least as large as the question. That was implemented years ago both in the client and in all server implementations, with the exception of Cisco that still doesn't seem to support this.

**Comment by jedisct1** [comment]
Also, with elliptic curve based signatures, that are supported by all modern resolvers and authoritative servers, DNSSEC signatures are fairly small.

Modern servers with support for DNSSEC are also typically the ones implementing the best defenses against common attacks.
