### ISSUE TITLE
Is there a line restriction on the blacklist

### ISSUE THREAD

**Issue by rdbox** [bitbeans/SimpleDnsCrypt#142]
I want to know if there are any restrictions on the number of rows of domains
For blacklist?
If there is a list of 1,000,000 lines this will affect speed?

**Comment by CHEF-KOCH** [comment]
Hes it has negative loading impact. That's why good filter list uses _atomizing_. See [here](https://github.com/gorhill/uBlock/wiki/Launch-and-filter-lists-load-performance). DNS/DnsCrypt was never developed to block such huge mass. Instead I always recommend to work with whitelist instead but that might be something for feature request.

**Comment by rdbox** [comment]
And the developer said that Simple DNSCrypt does not work with whitelists
Or something I did not understand correctly

**Comment by jedisct1** [comment]
There shouldn't be any problems with dnscrypt-proxy and 1,000,000 names or IPs being filtered, unless wildcards a present both after and before a name (`*example*` requires testing every position for every potential match, which is slow, but filtering `*.example.com` or `example.*` is very fast).

**Comment by rdbox** [comment]
And I do not download directly but through a file,
How do I specify a mask in the file?

Here is an example of a blacklist
 
 

![111](https://cloud.githubusercontent.com/assets/18515862/26760692/e373924e-4927-11e7-9aa5-e2bcfb68c3e0.jpg)
