### ISSUE TITLE
Script domain name listing creation

### ISSUE THREAD

**Issue by ghost** [bitbeans/SimpleDnsCrypt#146]
Hi
I do not know if someone here will help me or if I make my request in the right place but since my idea is based on a particular functioning of this software I hope that the community will be able to help me.
So I'm currently building my own DNS server using Unbound but what I want to achieve is a repetitive task (bash, I think) about the names of domains to be blacklisted by the software, Greatly appreciates the ability of DNSCrypt to create a complete file of domain names using scattered sources on the Internet while cleaning it and this is what I would need.

Could anyone help me with this, if of course this is possible ?

**Comment by jedisct1** [comment]
As you noticed, the client proxy itself supports this, via the [generate-domains-blacklist.py](https://github.com/jedisct1/dnscrypt-proxy/wiki/Blacklists) script.

It requires Python to be installed, but then it can work pretty much anywhere without any changes including on Windows.

SimpleDNSCrypt loads blacklists from text files. I'm not sure where they are stored, but they can certainly be updated directly by such a script instead of the GUI.

**Comment by Clu701** [comment]
In my opinion the ideal would be an adaptation, I have seven url concerning the sources because the purpose of my idea would be to let the script run autonomously. Every week it downloads the sources, adds the changes (as is currently done DNSCrypt) and then a command in bash to add what it takes so that the result can work with Unbound (cat /home/User/Desktop/Listing.txt | grep '^0\.0\.0\.0' | awk '{print "local-zone: \""$2"\" redirect\nlocal-data: \""$2" A 0.0.0.0\""}' >  /home/User/Desktop/Sources/domains-blacklist.conf).

Do you think that would be possible?

**Comment by jedisct1** [comment]
I don't think Unbound would let you filter patterns and IP addresses like dnscrypt-proxy does without writing a custom module.

**Comment by Clu701** [comment]
Not necessarily, the only part that will make the result work with Unbound is the line of code I provided. For the rest, this is the same as what DNSCrypt does, but simply write the url in the python script (or in a txt file, which will serve as the source file for the python script).
Sorry I'm really a novice in programming so my ideas may seem illogical in their constructions.
