### ISSUE TITLE
Censorship

### ISSUE THREAD

**Issue by robin98** [bitbeans/SimpleDnsCrypt#175]
Simple DNS Crypt can't bypass website filtering anymore, Like youtube.
Previously by using dnscrypt, we can bypass censorship for some websites, like youtube. but from last 3 months ago, we can't do it anymore.
when i ping youtube, it's return me real website ip address, that without using dns crypt, returns redirected ip address. but i can't access to youtube.
can you solve this issue?

**Comment by Shir01** [comment]
@robin98 
**Simple DNS Crypt** or it is better to say **dnscrypt-proxy**  is not a tool to bypass website filtering, sometimes it can help due to the methods that your ISP is using to filter traffic though. Based on the information you have provided I suggest you using VPN or encrypted proxy to bypass censorship.

**Comment by Rubber-Duckie** [comment]
Your ISP or LAN firewall has been updated to reverse lookup on IPs, when clearly it did not do so before. This means they no longer just rely on forward DNS request redirects. Consequently DNS Crypt cannot help you there, where it once used to because your DNS request was hidden, now they go further to find out the site your connecting to. Use a VPN as @Shir01 said, totally different solution. Try find a VPN provider who enables socks routing and portable clients that need no OS installation.

**Comment by robin98** [comment]
@Rubber-Duckie  My ISP can see what data i receiving from a dnscrypt server?
I thought when i using dns-crypt services, my both sent and receive data is encrypted.
But as you say, it's only encrypted from sender side(me or user)  and the queries of requests is not encrypted and everyone can see them.(Are we using a one-side encrypted connection?)
