### ISSUE TITLE
Same issue

### ISSUE THREAD

**Issue by lrayze** [bitbeans/SimpleDnsCrypt#184]
It was working fine but not anymore since yesterday, on my Windows 10 Pro Version 1709 build 16299.64 64bit.

![imagen](https://user-images.githubusercontent.com/23754665/33799407-f95b2526-dcf8-11e7-8b4f-a3e77f5ac835.png)

**Comment by Rubber-Duckie** [comment]
The issue seems to be, those who have exercised their own initiative to download and replace the resolver list and minisig, are now presented with a null reference error from bootstrap code. The error handling (having taken a quick look) could do with being more defensive, while being protective of passing invalid parameters to non-managed code. Better to perform existence checks on expected files at start-up (async) and present the user with a list of missing prerequisites as they are discovered. The app can take some time to start at times too, since the UI is not shown until a number of initialisation tasks are complete, it can be alarming. Perhaps these activities can be performed on a background thread fully async. Get the UI up immediately, it’s the very first thing to do.  Then show the traditional load screen spinner, letting the user know what the app is waiting on. The UX has a fault here too. But this error is indicative of these issues.

**Comment by Rubber-Duckie** [comment]
How you will let these users know a new version is available, is going to be a challenge, since the update code is unreachable since the error happens before the user has access to the UI and kills the application instead of placing the application into a limited mode of operation, while allowing other aspects unrelated to still function. Better to zone the application vertically, so that is becomes composited modules of functionality. only the UI controls related to a given zone are disabled when a show stopper affects that zone, but keep other areas functional.

**Comment by jedisct1** [comment]
@Rubber-Duckie weird, Github doesn't list any of your pull requests.

**Comment by Rubber-Duckie** [comment]
Perhaps this needs my help. I am not a big user of the project, but its value is indisputable.
