### ISSUE TITLE
How do I know SimpleDNSCrypt is working?

### ISSUE THREAD

**Issue by pbbuk** [bitbeans/SimpleDnsCrypt#189]
I have installed x64 version on Win10. From the Standard Settings screen, all seems ok, but the Properties of my Adapter still show 8.8.8.8 as DNS and if I change it to 127.0.0.1, the system can't resolve URLs. Also, the Live Log shows no entries, when switched on.

As per previous entries, I can't update Resolver list.

**Comment by Rubber-Duckie** [comment]
The issue is, those who are technically capable and have exercised their own initiative to download and replaced the resolver list and minisig, are now presented with an null reference error from bootstrap code. The error handling (having taken a quick look) could do with being more defensive, while being protective of passing invalid parameters to non-managed code. Better to perform existence checks on expected files at start-up and present the user with a list of missing prerequisites as they are discovered. The app can take some time to start too, perhaps some activities such as update check can be performed on a background thread fully async. Get the UI up first at least with spinner letting the user know what the app is waiting on.

**Comment by pbbuk** [comment]
I take it you are telling me that if things go wrong during the
installation of SimpleDNSCrypt, the program won't be able to tell me
about it.

Is it the case that my installation isn't working?

I had previously installed dnscrypt-proxy but after I asked a question
on its GitHub page, jedisct1 recommended the I shouldn't use it, but
should use SimpleDNSCrypt instead. Caught between two stools!

**Comment by nikw92** [comment]
Go to [dnsleaktest](https://dnsleaktest.com/) and do a standard or extended test and check the IP address of the servers identified. If the IP address of the identified server(s) matches the one you selected then most likely you have correctly configured Simple DNSCrypt.
