### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by rkwk** [bitbeans/SimpleDnsCrypt#203]
Sometimes a thread in the SimpleDnsCrypt.exe process starts using 100% of its CPU core and the application needs to be restarted to fix this. The stack trace shown by Process Explorer when this happens is:

ntoskrnl.exe!KiCpuId+0xaa
ntoskrnl.exe!MmUnlockPages+0xb52
ntoskrnl.exe!KeWaitForMutexObject+0x19f
ntoskrnl.exe!KeInitializeSemaphore+0x388
ntoskrnl.exe!KeExpandKernelStackAndCalloutEx+0x260d
ntoskrnl.exe!KiCpuId+0x24e6
PresentationFramework.ni.dll+0x384968
PresentationFramework.ni.dll+0x3a7f94
PresentationFramework.ni.dll+0x384968
PresentationFramework.ni.dll+0x3a8047
PresentationFramework.ni.dll+0x3a7f94
PresentationFramework.ni.dll+0x3b229d
PresentationFramework.ni.dll+0x3b1c45
PresentationFramework.ni.dll+0x33a4c1
PresentationCore.ni.dll+0x1ed172
PresentationCore.ni.dll+0x1fdd8d
PresentationCore.ni.dll+0x2051ce
PresentationCore.ni.dll+0x204ab4
PresentationCore.ni.dll+0x204a0e
WindowsBase.ni.dll+0xb9392
WindowsBase.ni.dll+0xb92d4
WindowsBase.ni.dll+0xbbab2
WindowsBase.ni.dll+0xbb9dc
WindowsBase.ni.dll+0x34ad13
WindowsBase.ni.dll+0xbb69e
WindowsBase.ni.dll+0xb7d15
WindowsBase.ni.dll+0xb7f0a
WindowsBase.ni.dll+0xb95bb
WindowsBase.ni.dll+0xb950b
WindowsBase.ni.dll+0xb9392
WindowsBase.ni.dll+0xb92d4
WindowsBase.ni.dll+0xb78c1
WindowsBase.ni.dll+0xb8dde
USER32.dll!gapfnScSendMessage+0x332
USER32.dll!GetThreadDesktop+0xd7
USER32.dll!CharPrevW+0x138
USER32.dll!DispatchMessageW+0xf
WindowsBase.ni.dll+0xe9350
WindowsBase.ni.dll+0xb58c9
WindowsBase.ni.dll+0xb55c2
PresentationFramework.ni.dll+0x2afe62
PresentationFramework.ni.dll+0x2afcf8
PresentationFramework.ni.dll+0x2afa9f
clr.dll+0xeb16
clr.dll!LogHelp_TerminateOnAssert+0x58a4
clr.dll!LogHelp_TerminateOnAssert+0x6d14
clr.dll!DllRegisterServerInternal+0x3103c
clr.dll!DllRegisterServerInternal+0x30fa0
clr.dll!DllRegisterServerInternal+0x31716
clr.dll!DllRegisterServerInternal+0x317b9
clr.dll!DllRegisterServerInternal+0x31116
clr.dll!_CorExeMain+0x1c
ntdll.dll!RtlInitializeExceptionChain+0x63
ntdll.dll!RtlDeactivateActivationContextUnsafeFast+0x35f

**Comment by rkawulak** [comment]
Another case with a slightly different stack trace. The interesting thing is the call to LogHelp_TerminateOnAssert, indicating that there might be a failed assertion somewhere, but for some reason the program stays alive with high CPU usage instead of terminating.

ntoskrnl.exe!KiCpuId+0xaa
ntoskrnl.exe!MmUnlockPages+0xb52
ntoskrnl.exe!KeWaitForMutexObject+0x19f
ntoskrnl.exe!KeInitializeSemaphore+0x388
ntoskrnl.exe!KeExpandKernelStackAndCalloutEx+0x260d
ntoskrnl.exe!KiCpuId+0x24e6
clr.dll!DllUnregisterServerInternal+0x8c72
clr.dll!DllUnregisterServerInternal+0xbe7f
clr.dll!DllUnregisterServerInternal+0x92df
clr.dll!DllUnregisterServerInternal+0x861d
clr.dll!DllUnregisterServerInternal+0x8b2b
clr.dll!DllUnregisterServerInternal+0x88ae
clr.dll!GetPrivateContextsPerfCounters+0x1eaad
clr.dll!DllUnregisterServerInternal+0x528a
clr.dll!DllUnregisterServerInternal+0x52e5
clr.dll!DllUnregisterServerInternal+0x5456
clr.dll!LogHelp_TerminateOnAssert+0x6667
clr.dll!LogHelp_TerminateOnAssert+0x66f6
clr.dll!LogHelp_TerminateOnAssert+0x67b5
PresentationCore.ni.dll+0x1fb542
PresentationCore.ni.dll+0x1fb4a0
PresentationCore.ni.dll+0x1fb451
PresentationCore.ni.dll+0x1fb41d
PresentationCore.ni.dll+0x1fb3f9
PresentationCore.ni.dll+0x1fa8a1
clr.dll!DllUnregisterServerInternal+0x511b
clr.dll!DllUnregisterServerInternal+0x53c0
