### ISSUE TITLE
[Request] Update dnscrypt-proxy In App

### ISSUE THREAD

**Issue by zero77** [bitbeans/SimpleDnsCrypt#242]
Can you consider checking for and updating dnscrypt-proxy at the same time as SimpleDnsCrypt does.
Thanks

**Comment by jedisct1** [comment]
It's already the case. Christian quickly publishes new versions of Simple DNSCrypt after a new version of the proxy is out.

**Comment by jedisct1** [comment]
But if something changes in the configuration file, it may break Simple DNSCrypt, and people will be mad :)

**Comment by zero77** [comment]
What about making it optional and giving an option to downgrade again if it breaks.

**Comment by jedisct1** [comment]
Because if it breaks, people are not going to to look for an option to downgrade, or even think that it is related to SimpleDNSCrypt, more specifically a dependency of it they never heard about. They are just going to complain that Internet is broken, and eventually that deinstalling SimpleDNSCrypt fixes it.

**Comment by bitbeans** [comment]
@zero77 if you can`t wait just use the CI builds: https://github.com/bitbeans/SimpleDnsCrypt#preview-download-ci :)

**Comment by zero77** [comment]
@jedisct1 
Ok, that makes sense.

@bitbeans 
Its not so much I can’t wait, I just thought it may make things easier and more officiant.

**Comment by jillmorinYXP** [comment]
You could use Squirrel or pyup-bot, to keep dnscrypt-proxy up to date. @bitbeans 
https://pyup.io/
https://github.com/Squirrel/Squirrel.Windows
