### ISSUE TITLE
dnsleaktest.com detects not only the OpenDNS and Google servers, but also my ISP ones.

### ISSUE THREAD

**Issue by liubomirwm** [bitbeans/SimpleDnsCrypt#252]
I have enabled the service and also selected all of the adapters. I have selected OpenDNS and Google on the resolvers tab. When i test with dnsleaktest.com my own ISP servers are also found. When i check the IPv4 settings of my OS the DNS is set to automatically detect DNS settings. Previously (some months ago) i believe it was 127.0.0.1.

**Comment by slyphnier** [comment]
the quickest way probably, just uninstall and re-install 
so it will configure everything again 

also you need to set (make sure) your DNS is set to 127.0.0.1 not automatic
because DNScrypt the one do DNS work and its on your pc (127.0.0.1)

probably some update, either simplednscrypt update or windows update or driver update revert the setting to automatic

**Comment by liubomirwm** [comment]
It is a new installation of version 0.5.2.

**Comment by liubomirwm** [comment]
Today SimpleDNSCrypt updated to version 0.5.3 with dnscrypt-proxy version 2.0.6 and now the system has 127.0.0.1 in the DNS settings and the ISP DNS is no more detected.
