### ISSUE TITLE
Add Tenta to Available Resolvers

### ISSUE THREAD

**Issue by DaBomby** [bitbeans/SimpleDnsCrypt#285]
Is it possible to add the Tenta servers to the list of available resolvers? More details about the Tenta system here: https://tenta.com/dns-setup-guides.

Thanks in advance.

**Comment by jedisct1** [comment]
Tenta doesn't support DNSCrypt nor DoH yet, because the standard DNS library they are using didn't support any of these until recently.

DoH has been implemented since (https://github.com/miekg/dns/commits/doh1), so Tenta may eventually support it once a new version of that library with this gets released.
