### ISSUE TITLE
Simple question - CloudFlare server country

### ISSUE THREAD

**Issue by Decopi** [bitbeans/SimpleDnsCrypt#310]
Hi,

I installed today SimpleDNSCrypt.

I chose CloudFlare as unique resolver.
I tested with https://dnsleaktest.com/ , and the result is that I am connected to CloudFlare at United Kingdom. The problem is that I am in Brazil. So I have a huge delay with United Kingdom.

CloudFlare has servers in Brazil, in my own City (São Paulo).
My simple question is: How can I use CloudFlare servers here in São Paulo - Brazil?

Thanks!

**Comment by gsarcov** [comment]
The IP location is irrelevant since Cloudflare is using an Anycast Network. This means that an IP address can be logically registered in the US, for example, but serve local traffic in any of the 151+ data centers or PoP's (Points of Presence) around the world. Here are a few excerpts taken from the Cloudflare learning Center:

"With an Anycast network, instead of one origin server taking the brunt of the traffic, the load can also be spread across other available data centers, each of which will have servers capable of processing and responding to the incoming request. This routing method can prevent an origin server from extending capacity and avoids service interruptions to clients requesting content from the origin server."

"What is the Difference between Anycast and Unicast?
Most of the Internet works via a routing scheme called Unicast. Under Unicast, every node on the network gets a unique IP address. Home and office networks use Unicast; when a computer is connected to a wireless network and gets a message saying the IP address is already in use, an IP address conflict has occurred because another computer on the same Unicast network is already using the same IP. In most cases, that isn't allowed.

Unicast CDN diagram

When a CDN is using a unicast address, traffic is routed directly to the specific node. This creates a vulnerability when the network experiences extraordinary traffic such as during a DDoS attack. Because the traffic is routed directly to a particular data center, the location or its surrounding infrastructure may become overwhelmed with traffic, potentially resulting in denial-of-service to legitimate requests.

Using Anycast means the network can be extremely resilient. Because traffic will find the best path, an entire data center can be taken offline and traffic will automatically flow to a proximal data center.

How does an Anycast network mitigate a DDoS attack?

After other DDoS mitigation tools filter out some of the attack traffic, Anycast distributes the remaining attack traffic across multiple data centers, preventing any one location from becoming overwhelmed with requests. If the capacity of the Anycast network is greater than the attack traffic, the attack is effectively mitigated. In most DDoS attacks, many compromised "zombie" or “bot” computers are used to form what is known as a botnet. These machines can be scattered around the web and generate so much traffic that they can overwhelm a typical Unicast-connected machine.

Anycast/Unicast under attack

A properly Anycasted CDN increases the surface area of the receiving network so that the unfiltered denial-of-service traffic from a distributed botnet will be absorbed by each of the CDN’s data centers. As a result, as a network continues to grow in size and capacity it becomes harder and harder to launch an effective DDoS against anyone using the CDN.

It is not easy to setup a true Anycasted network. Proper implementation requires that a CDN provider maintains their own network hardware, builds direct relationships with their upstream carriers, and tunes their networking routes to ensure traffic doesn't "flap" between multiple locations. This Cloudflare blog post explains how Cloudflare uses Anycast to load balance without load balancers."
For graphs and an in depth overview visit the following pages: 

https://www.cloudflare.com/learning/cdn/glossary/anycast-network/

https://blog.cloudflare.com/cloudflares-architecture-eliminating-single-p/

https://blog.cloudflare.com/tag/anycast/

Best,

George

**Comment by Decopi** [comment]
Thank you @gsarcov and @jedisct1 .

Playing with the SimpleDNSCrypt settings, at "Resolver" tab, I unchecked CloudFlare IPV6, remained checked only CloudFlare IPV4... and it worked! I tested, and now I am connected only to CloudFlare São Paulo Brazil.

Thank you again

**Comment by Decopi** [comment]
Thank you @gsarcov and @jedisct1 .

Playing with the SimpleDNSCrypt settings, at "Resolver" tab, I unchecked CloudFlare IPV6, remained checked only CloudFlare IPV4... and it worked! I tested, and now I am connected only to CloudFlare São Paulo Brazil.

Thank you again
