### ISSUE TITLE
Simple questions: CloudFlare DNS-over-TLS

### ISSUE THREAD

**Issue by Decopi** [bitbeans/SimpleDnsCrypt#311]
Hi,

I read that:
1) DNSCrypt will be abandoned.
2) DNSCrypt' developer recommends DNS-over-TLS.
3) CloudFlare suports DNS-over-TLS.

Please, my questions (apologizing in advance for my ignorance):

If I use CloudFlare DNS-over-TLS, I still need DNSCrypt?

CloudFlare informs that DNS-over-TLS works only on port 853.
How do I configure DNSCrypt in order to work with CloudFlare on port 853?

Thank you!

**Comment by jedisct1** [comment]
1. No. It's never been as active as it is today. It's just a protocol. Version 2 of a client implementation named dnscrypt-proxy was recently released. This version is way better than versions 1.x and virtually everybody's using version 2 now. So its author is focused on this new version, and doesn't have any reason to keep working on the legacy version. This is what has been "abandoned". An obsolete app, since there is a way better replacement.

2. No. If I had one drink too many, I would describe this as a scam by some organizations to get funding. This would have been an okay solution 10 years ago, but it's completely tacky in 2018. This is a regression, where problems that have been already solved are described as needing to be reinvented. It has zero advantages over other solutions except making you feel like you're traveling back in time.

3. Not really. Technically, they do. But if you listen to their presentations the only thing they will mention is DNS-over-HTTPS.

You can't use DNS-over-TLS using dnscrypt-proxy (and SimpleDNSCrypt).

**Comment by jedisct1** [comment]
The TheBestVPN page you are referring to was designed to trick Google and other search engines to redirect users looking for anything related to privacy to this company's product.

This is a shady marketing strategy called Blackhat SEO. That company sent massive spam to individuals and mailing lists in order to have people add links to that page to increase that company's popularity on search engines.

The actual information on this page is complete bullshit; its entire point is to be a click-bat and to include keywords to trick search engines.

It's not important to have DNS-over-TLS, especially between clients and resolvers. Cloudflare supports DNS-over-HTTPS. So if you are using DNSCrypt, just select "Cloudflare" in the resolvers list and you're good to go.

**Comment by Decopi** [comment]
Wow! Amazing answer @jedisct1 ! Today, you indeed teach me a lot. Thank you!

It is incredible nowadays, the degree of "safe opinion" this fake texts achieve.
And this is not happening only with tech texts, but also with politic texts, pseudoscience, economy, general opinion, news etc texts. Sadly, we readers must check and recheck sources before reading this garbage texts.
Thanks again @jedisct1 .

So, by the end, if I understand you, everything is "ok" with my SimpleDNSCrypt + CloudFlare, and I don't need to change nothing. Right? And abusing from your patience: At every Windows boot, do I need to execute SimpleDNSCrypt? I just execute SimpleDNSCrypt only when I want to change settings. While not executing, everything works "ok", the 127.0.0.1 is working, the dnscrypt-proxy.exe service is working etc. Sorry for the silly question: Do I need to to execute SimpleDNSCrypt at every Windows boot?

Thanks!

**Comment by jedisct1** [comment]
Hi Decopi,

I think it will be automatically restarted. But you can always go to a site such as http://dnsleaktest.com/ to verify that it is the case after a reboot!

**Comment by jedisct1** [comment]
Yep, you are correct :)

**Comment by Decopi** [comment]
@jedisct1 , I don't want to open a new question, so please allow me one more different question question (lol):

I read the difference between DNSCrypt and DNS over HTTPS (DoH). I confess, I didn't understand the explanation, too technical for me.

I know CloudFlare offers DNS over HTTPS (DoH).
But I also know that Firefox soon will use DNS over HTTPS (DoH). And I am using Firefox.

Based on your experience/knowledge, which one is better or least bad?
DNSCrypt + CloudFlare?
Or CloudFlare DNS-over-HTTPS (without DNSCrypt)?
Or is it possible to use both DNSCrypt + CloudFlare DNS-over-HTTPS (with future versions of Firefox)?

If you can't answer me, don't worry, I'll open a new question.
Thanks in advance!

**Comment by jedisct1** [comment]
This article may be worth reading: https://arstechnica.com/information-technology/2018/04/how-to-keep-your-isps-nose-out-of-your-browser-history-with-encrypted-dns/

Firefox already supports DoH :) But this is quite new, and requires going to the advanced settings. 

However, changing the DNS settings in Firefox only affects web browsing. Your computer is constantly sending DNS queries that have nothing to do with web browsing. Other applications are phoning home, checking for updates, etc.

So, changing the global DNS settings is more effective than just within a single application.

Cloudflare doesn't support DNSCrypt (yet?), but they have a good DNS-over-HTTPS implementation, so just use Cloudflare with DoH using SimpleDNSCrypt :)

**Comment by Decopi** [comment]
@jedisct1 Thanks a lot for the article, I will read calmly tomorrow.

Following your suggestion, I tried to setup CloudFlare DNS-over-HTTPS... but it is nightmare, at least for me. Most of the instructions at CloudFlare webpage are for Linux an MacOS. And everything is explained in tech language.

I tried to ask for help at the CloudFlare forum, and most of the users there are Linux and MacOS.

I can make CloudFlare DNS-over-HTTPS work in Firefox, but only in Firefox, and only by entering website by website, in a kind of list. A nightmare!

Sorry to ask, do you know any easy way to install CloudFlare DNS-over-HTTPS in Windows 10, working globally for every browser in my computer, every app, website, any traffic communication in my computer?

**Comment by jedisct1** [comment]
Install SimpleDNSCrypt and select "Cloudflare" in the list of available resolvers. This is all you need.

**Comment by Decopi** [comment]
OK @jedisct1 . Thanks.
I thought it was needed some kind of complex configuration.

Just to be 100% clear here: By using DNSCrypt + CloudFlare resolver... I will have both benefits of DNSCrypt + CloudFlare with DoH?

I just ask again, because reading the CloudFlare/DoH' tutorials, and reading other tutorials I am receiving at CloudFlare forum, CloudFlare with DoH requires the installation of some executables, as well as it also needs many command lines and configurations. It seems not easy to make it work. Somehow after suffering reading CloudFlare turorials, it is difficult for me to believe that just using DNSCrypt + CloudFlare resolver... will do the job.

**Comment by jedisct1** [comment]
Yes, it will do the job. Simple DNSCrypt fully supports DNS-over-HTTPS, you don't need to fiddle with the command line.
