### ISSUE TITLE
It will not OPEN.

### ISSUE THREAD

**Issue by Eternal73** [bitbeans/SimpleDnsCrypt#338]
I've uninstalled/re-installed it just, will not open. Firewall is off. Any insight would be appreciated. Microsoft .Net Framework 4.7.1 (windows 7)
Compaq Presario CQ57-229WM
Processor AMD C-50
64 bit system

**Comment by kuchienkz** [comment]
I have the same problem with you, in my case, the service is failed to start because somehow, it is not installed. Fixed it by re-installing the service with command prompt:

1. Open command prompt as Administrator

2. Navigate to Simple DNSCrypt installation directory. In my case: 

> cd "C:\Program Files\bitbeans\Simple DNSCrypt x64\dnscrypt-proxy"

3. Then run:

> dnscrypt-proxy -service install

4. It should be done in no time, next, start the service:

> dnscrypt-proxy -service start

5. Finally, try to open the app again!

For step 1 to 4, you only have to do it ONCE. The installed service should start automatically on next boot.

Good luck!

**Comment by Eternal73** [comment]
Thanks for the info, after following your steps. The application opened and is running. Thank you so much.

**Comment by kuchienkz** [comment]
You're welcome and congrats!
