### ISSUE TITLE
query log & domain block log empty

### ISSUE THREAD

**Issue by erwinsya** [bitbeans/SimpleDnsCrypt#352]
I just installed manually over 0.5.6 >0.5.7>0.5.8 and found empty query..keep waiting DNS queries

I look into bitbeans dir and not found log there. Any suggests ? Is it culprit updated from 0.5.6 or just jump from 0.5.6 to 0.5.8 manually

**Comment by zelinder** [comment]
I have had this same issue for many versions now.  It strictly happens when I am using NordVPN. My computer is the "Global Resolver" for the network.  My DHCP server point all devices to my computer for DNS queries.  When the VPN is on it just says "waiting for DNS queries".  All of the devices and computers get their DNS queries just fine through my computer.

I understand that my computer will get its DNS queries through the VPN.

- When the VPN is on none of the device queries get logged.
- When the VPN is off all the device queries get logged correctly.

I imagine that it is the virtual network adapter that NordVPN creates that kind of freaks it out.

If you are using a VPN try logging with and without the VPN connected.
