### ISSUE TITLE
[Question] should user updating DNScrypt manually ?

### ISSUE THREAD

**Issue by slyphnier** [bitbeans/SimpleDnsCrypt#360]
I need some info here

in code, i saw update to dnscrypt to version 2.0.17 since last month 
should i update it to that version manually  (replacing the 2.0.16 version) ?

Or better leave at 2.0.16 because there might some conflict between simplednscrypt and version 2.0.17 ?

sorry for being lazy, i should try it myself and see if there any issue, then roll-back to previous version
but i think this QA good for clearing out others that have same thinking like me 

thanks

**Comment by Skcyte** [comment]
While I want to get the latest library but for me there's a reason why this is called as it is. Because probably the majority including myself doesn't know how to edit the code and just want to have a working program. As far as I understand coding, it's not that simple as copying and pasting library from point A to B. But if you want to edit and make it your own then share it maybe you could fork the project and update it.

**Comment by bitbeans** [comment]
I will push an update as soon as possible :) sorry for the delay
