### ISSUE TITLE
Simple DNSCrypt do not startup

### ISSUE THREAD

**Issue by wamojira** [bitbeans/SimpleDnsCrypt#445]
Hi!

Simple DNSCrypt do not startup with WIN 8.1 x64. I run it with admin rights, reinstall it and it does not work. I have to run it manually. Please help.

**Comment by AKmatiAK** [comment]
same issue on windows 7 x64

**Comment by bitbeans** [comment]
What does it mean doesn't start? Does dnscrypt-proxy not start or can Simple DNSCrypt not be opened? Are there log files?

**Comment by AKmatiAK** [comment]
dnscrypt client doesn't load, dnscrypt-proxy too. I have to run app and then when I enter it windows service switch is off every time after restart. App is very complicated overall, I figured that I have to click connection icon (broadband connection 3, bottom of settings) and then it works correctly. I had also problem how to enter app, because first i have to open it in windows, then double click in taskbar icons. Is there also option to enable only DoH servers?

**Comment by AKmatiAK** [comment]
When I uncheck DNSCrypt at main menu do I get only DoH servers then?

**Comment by AKmatiAK** [comment]
ok, update: i do not need to check broadband connection icon at bottom of main settings, but autostart is still broken. does "dnscrypt client proxy" service in services.msc have to be automatic or manual?

**Comment by bitbeans** [comment]
it must be on: automatic 
maybe you try uninstall the service or the whole application

**Comment by AKmatiAK** [comment]
tried and doesn't work. i also tried adding simple dnscrypt to autostart. doesn't work too, nor app nor service loads.

**Comment by Agych** [comment]
Same issue here, the program does not autostart with the OS.
Have to start it manually every time after boot.
Windows 7 SP1 x64.

Also would like to ask for a "Autostart with Windows" option in the settings.

**Comment by skeith** [comment]
On a fresh machine with Windows 10 pro, SimpleDNSCrypt has its service installed, but on every boot or reboot, it doesn't start itself (the service)

If we start the app, it will say the service not started (it's on OFF state) but the service state is installed and I have to turn on the service manually. This render the service useless despite it is set to Automatic
