### ISSUE TITLE
Minimize to system tray

### ISSUE THREAD

**Issue by Zhouxing-Su** [bitbeans/SimpleDnsCrypt#56]
Should we keep the window opened after enabling DNSCrypt service?
If we have to, could you please provide a button for minimizing to tray?

**Comment by bitbeans** [comment]
No you can close Simple DNSCrypt.
The dnscrypt-proxy service is still running in background.

**Comment by monstertruckpa** [comment]
but we want that the icon on System Tray showing activity, Sometimes the ip static or dhcp connection falls ,  and the DNS on the network options too 127.0.01 ipv4 disappears, And that's why it's more practical to have the icon in the background, also The program will show when the dnscrypt proxy service 1 and 2, appears off, Or the connection is gone from the network card. Thanks bitbeans for your great things and developments.
