### ISSUE TITLE
Win7 Freeze

### ISSUE THREAD

**Issue by robynasi** [bitbeans/SimpleDnsCrypt#81]
Hi! My Windows 7 x64 freeze after some time after enabling the DSCrypt and I need to force restart my notebook.

**Comment by bitbeans** [comment]
Need some more details. Sorry. Try 0.3.8.

**Comment by robynasi** [comment]
Same with 0.3.8.

**Comment by bitbeans** [comment]
Are sure it`s a Simple DNSCrypt problem?

Note: Simple DNSCrypt is not DNSCrypt.

**Comment by robynasi** [comment]
Yes, it only happen when DNSCrypt is active on a card

**Comment by jedisct1** [comment]
Simple DNSCrypt doesn't do anything low-level. The most "intrusive" change is does is change the DNS configuration, which is never supposed to make an operating system freeze. Bugs in Simple DNSCrypt can just make it crash itself, but should not have any side effects on the kernel.

The root cause making your system unstable is likely to be something else, maybe even a hardware issue or some malware lying around.

**Comment by robynasi** [comment]
If can be useful..the same thing happens when using TOR (that I think use something similar to solve DNS). Also this issue is for both WiFi or LAN card.
